name: Deploy Lambda Function

on:
  push:
    branches:
      - main

env:
    AWS_REGION: us-west-1
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2 # checkout the commit that triggered this action

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-1

    - name: Build Docker Image
      run: docker build --platform linux/amd64 -t fake-news-docker docker_image_files

    # Below, we use the GitHub Action: aws-actions/amazon-ecr-login
    # This will get the 'registry' from output from the action: steps.login-ecr.outputs.registry
    # The value of 'registry' is my ECR, which contains my account number, with the syntax: 123456789012.dkr.ecr.us-west-1.amazonaws.com
    - name: Tag Docker Image
      run: docker tag fake-news-docker:latest ${{ steps.login-ecr.outputs.registry }}/fake-news-model:latest
      #docker tag fake-news-docker:latest 851725529671.dkr.ecr.us-west-1.amazonaws.com/fake-news-model:latest

    - name: Push Docker Image to ECR
      run: docker push ${{ steps.login-ecr.outputs.registry }}/fake-news-model:latest
      #docker push 851725529671.dkr.ecr.us-west-1.amazonaws.com/fake-news-model:latest

    - name: Update Lambda Function
      run: aws lambda update-function-code --function-name predict-fake-news --region us-west-1 --image-uri ${{ steps.login-ecr.outputs.registry }}/fake-news-model:latest
      #aws lambda update-function-code --function-name predict-fake-news --region us-west-1 --image-uri 851725529671.dkr.ecr.us-west-1.amazonaws.com/fake-news-model:latest
